### ISSUE TITLE
Some cast operators are broken

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#121]
Some cast operators are broken.

Trying to cast anything into a number or a color gives a parsing error.
Casting a number to vector yields `cannot convert number to color`. (From what i can tell from the source converting a number to a color is allowed.)

Also the cast from bool to number would behave inconsistent, if it would work. `bool -> number -> bool` always yields `false`.

The other casts may exhibit some unexpected behaviour aswell.

**Comment by MerlinofMines** [comment]
Aww, looks like this is a bug in unsupported cases.  I flipped Vector and Color.

A number cannot be cast to a vector per the cast map, but the failure message is "Color" incorrectly.  Similarly, the failure mode for "color" is set to "vector".  Whoops.

Can be fixed for next minor version (1.1.1)

**Comment by MerlinofMines** [comment]
And i should add tests around all the casting functions (including failure modes) to make sure this is caught properly.

**Comment by MerlinofMines** [comment]
As for the boolean casting...ya i did some bad things for numeric/boolean casting in order to support comparison/equality and those things are coming back to haunt me.  Time to take another look at this! :)
