### ISSUE TITLE
Split / Join Support

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#130]
It'd be nice to be able to split string content by a given string delimiter, with the result being a list.  This could be used for parsing LCD output by line, for example.

Conversely, it'd be nice to join a list of values by a delimiter to create a string, for nice easy output of lists (comma separated, line separated, etc).  

I suggest "split" and "join".  "join/joined" may have to be shifted to this new operation?

```
#Split
set myOutputLines to my "Display Panel" text split "\n"
for each outputLine in myOutputLines
  Print "Output Line: " + outputLine

#Join
set myList to [1,2,3]
set myString to myList joined ", "
print myString
#1, 2, 3
```

**Comment by agonzalezloz** [comment]
Of course, it would be an excellent implementation.
Thanks
