### ISSUE TITLE
Suprising behaviour of some casts

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#139]
This splits the behavioral changes mentioned #121 and #131 into a seperate issue.

The following cast behaviour is surprising.
- bool <-> number
    `true -> 0 -> false`
     `false -> -1 -> false`
- color <-> vector
    `255:255:255 -> #FFFFFF -> 1.0:1.0:1.0 -> #010101 -> 0.003922:0.003922:0.003922 -> #000000 -> 0:0:0`

**Comment by MerlinofMines** [comment]
Resolved by #140
