### ISSUE TITLE
Dynamic ItemName Parsing

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#148]
The current Item Name parsing for inventories and production queues relies on hardcoded mappings between specific names and in game Blueprint/Item names.

As such, only vanilla items are currently supported for inventory management. We should revisit this and see if there is a way to dynamically resolve these such that 3P can also be used.

As part of this, we might also be able to add support for printing out the needed component items for any block, as well as print out the total components needed for finishing a blueprint from a projector, which would be handy

**Comment by MerlinofMines** [comment]
Related article on this that indicates it may not be possible, unfortunately:
https://steamcommunity.com/app/244850/discussions/0/1743394605019944592/

**Comment by MerlinofMines** [comment]
We still might be able to fall back to the "SubTypeId" or similar for doing dynamic resolution.  It wouldn't be as user friendly but would be able to support non-vanilla items & blueprints.   Will keep noodling here.

**Comment by jgersti** [comment]
If some of the ModAPI changes that where presented at the keen stream last(?) week triggle down to the programmable block the localization files might be accessible in the future.

**Comment by MerlinofMines** [comment]
I imagine a property that would print out the TypeId & SubTypeIds for all items in an inventory or production queue, and 1 or 2 commands for adding item names (and blueprints) to the registry using <friendlyName> <SubTypeId>. So in the setup of your script you can manually add more words for the items. That would let you only add what you need, and we could add example setup scripts to the website for commonly used mod items.

**Comment by MerlinofMines** [comment]
> If some of the ModAPI changes that where presented at the keen stream last(?) week triggle down to the programmable block the localization files might be accessible in the future.

That would be very useful indeed!

**Comment by MerlinofMines** [comment]
Ok, gonna start with ability to parse any dynamic TypeId/SubTypeId, and then add commands for adding customer keywords to item/blueprint mappings.
