### ISSUE TITLE
Parse GPS Coords as Vector

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#151]
It'd be nice if GPS coordinates could be directly parsed as vectors, can we make this happen?

**Comment by MerlinofMines** [comment]
A new primitive type might actually be useful for this, so that we can retain the label/color support while still having vector cast support.

**Comment by jgersti** [comment]
see #169 for some thoughts

**Comment by MerlinofMines** [comment]
This is already supported
