### ISSUE TITLE
`RotationIndicator`, `RollIndicator`, `MoveIndicator`  are mouse/controller sensitivity dependant

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#161]
see the notes at https://github.com/malware-dev/MDK-SE/wiki/Sandbox.ModAPI.Ingame.IMyShipController

For the normal PC user (mouse+keyboard) this only affects `RotationIndicator`

**Comment by MerlinofMines** [comment]
This behavior is intended, as it means that your sensitivity settings will change the speed at which things are moving, especially when using the mouse.  I tried to set the scaling values so that the default sensitivity settings equate to values of "1" at maximum rotation / movement using default sensitivity.

What is the specific concern and/or proposal for a fix?

**Comment by jgersti** [comment]
My solution would be to use the sign on everything so it has a reproducible and welldefined value.

**Comment by MerlinofMines** [comment]
You'd sacrifice fluid feeling rotation control via mouse if only using the sign.  I'm not sure I wanna give that up.  IMO if you change your sensitivity settings and want to directly use hen you'll have to scale.  You can also check the sign in the script.  We could add a quantized operation to map values to -1,0,1 for a given vector or number, perhaps?

**Comment by jgersti** [comment]
My initial problem was that i noticed that the rotation values changed accidently hit the dpi buttons on my mouse.
This means the maximum absolute value changes dependending on hardware specs and OS settings.

I would be ok if we just add a standalone the sign function for numbers (`Math.Sign`) and vectors (`Vector3D.Sign`).

**Comment by MerlinofMines** [comment]
Cool.  Let's add the operation and get the best of both.  We should also update the docs around inputs to clarify that they are sensitivity dependent and that you can quantize using the new operation.  I like quantize and sign as keywords.

**Comment by jgersti** [comment]
Opened a new Issue for the input documentation  #164.
