### ISSUE TITLE
Dynamic Function Calls

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#172]
It'd be nice if you could dynamically invoke a function using ```call variable``` or ```goto variable```

This would require some new parsing rules.  Also, safety on the function name as well as parameter count would have to be best effort.

Note that we may have to relax some of the current function definition validation for this, as the function being invoked won't be known until runtime.

**Comment by jgersti** [comment]
Shouldn' t  `tell self to run variable` already work?

**Comment by MerlinofMines** [comment]
the effect of the above would spin off a new request thread, whereas a dynamic function call would block on the same thread in which it was invoked, so the behavior is quite a bit different.

I'll take a look at this one
