### ISSUE TITLE
BiOperand Priority

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#177]
The priority of  the power operator `^` needs to be higher than that of multiplikation `*`, division `/` and modulo `%`.

**Comment by MerlinofMines** [comment]
The current pattern has been to keep adding more operation tiers.  I wonder if there's a more scalable way to specify this ordering which doesn't add more characters but makes it easier to add more tiers in the future.

**Comment by jgersti** [comment]
well...
all the boolean and comparison operators already are effectively "tier 2.5" with the difference they need to be covered by rules for transformations.
this means handling of tier 0..2 and tier 3 cannot be combined without disrupting "tier 2.5".

maybe adding a new `BiOperandProcessor` that handles the priority which is added as a new value on a unified `BiOperandCommandParameter` for tier 0..2

**Comment by MerlinofMines** [comment]
I think i've got a better pattern working locally, will send out a PR to add this tier shortly
