### ISSUE TITLE
Attach/Detach Support

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#183]
Currently Pistons and Wheels lack attach/detach support, even though there is an action for this on these blocks.  Perhaps we can enable this using the Connected property?

As an action, the attach/detach action would have to be best effort

```
while "My Wheel" is not attached
  attach "My Wheel"
```

**Comment by jgersti** [comment]
Changes to support that are minimal. The documentation just needs a very clear, pointed and strong remark that this might invoke Clang.
