### ISSUE TITLE
[Feature Request] Velocity Property Improvements

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#194]
**Is your feature request related to a problem? Please describe.**
I'm noticing some inconsistency between Parachutes & Cockpits now that I think we should address.  Some properties, like "Gravity", return vectors (which is useful for identifying orientation WRT to a nearby planet), whereas velocity only returns the magnitude of the velocity, which is much less useful.  You can use directional vectors, sure, but the velocity returned directly as a vector might be more useful.  You can always do "abs myVelocityVector" to get the magnitude, anyway

**Describe the solution you'd like**
"velocity" by itself should return a vector, for both cockpits and parachutes, indicating the direction of travel in world coordinates.

We should add a TypeHandler so that if you compare it a number, length is used (this may already happen actually, may not be needed?).  Default should be vector.

**Comment by MerlinofMines** [comment]
We should also consider separating speed & velocity.  Speed = magnitude.  Velocity = vector

**Comment by jgersti** [comment]
vector number comparison do compare length so that would already work.

**Comment by MerlinofMines** [comment]
trying to separate "speed" is a little more hairy...will require a few annoying changes.  For now I will just change velocity for cockpits/parachutes to use vectors consistently
