### ISSUE TITLE
[Feature Request] Searchlight Support

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#205]
**Describe the solution you'd like**
the Warfare 2 update added "Searchlight" support, which is both a turret and a light.

It'd be nice to extend the turret support with searchlight support, and re-add the light properties for searchlight (may require using custom properties).

It shows up neither in lights nor in turrets, so not sure what this thing is yet.

**Comment by jgersti** [comment]
On the keen discord Digi said that the searchlight does not have a proper interface yet. the best you can do is `IFunctionalBlock` (?) and its `subtypeid` and the old property and action methods.

**Comment by MerlinofMines** [comment]
Ya I think i'll wait a bit and see if they add interface definitions, before implementing a custom one using direct properties.
