### ISSUE TITLE
[Feature Request] Properties for `CustomData` and `DetailedInfo`

### ISSUE THREAD

**Issue by jgersti** [MerlinofMines/EasyCommands#210]
**Is your feature request related to a problem? Please describe.**
Quite a few properties are hidden behind `DetailedInfo` (mostly power related stuff). Many scripts are configured with `CustomData`. Modifying this on the fly increases interoperability with such scripts.

**Describe the solution you'd like**
Add a readonly property `DetailedInfo`and a readable & writable property for `CustomData` to `terminal`.

**Comment by MerlinofMines** [comment]
Yep that sounds about right.  How about 

DATA:
data,custom data  

INFO:
info,detail

Terminal block is right.  We should think about what would be done for inventories and displays
