### ISSUE TITLE
[Feature Request] Custom Turret Controller Support

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#212]
**Describe the solution you'd like**
There's a new custom turret controller block which has some nice properties.  It'd be nice to create a controller for this.

**Describe alternatives you've considered**

**Additional context**

**Comment by jgersti** [comment]
Malware did update the hie wiki. So here we go:
https://github.com/malware-dev/MDK-SE/wiki/SpaceEngineers.Game.ModAPI.Ingame.IMyTurretControlBlock

**Comment by jgersti** [comment]
Maybe take a look at the TCES script from wiplash  [Workshop](https://steamcommunity.com/workshop/filedetails/?id=2753791447)/[Githunb](https://github.com/Whiplash141/SpaceEngineersScripts/blob/master/Released/TCES.cs).

**Comment by MerlinofMines** [comment]
Resolved by #228
