### ISSUE TITLE
[Feature Request] Grid BlockHandler

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#222]
**Describe the solution you'd like**
We should add support for getting/setting values from the grid, such as the grid name, grid size, whether or not it is static, etc.

I suggest a "GridHandler" that returns ProgrammableBlock.Me.CubeGrid.  Can have properties for the size, name, and maybe static?

**Comment by MerlinofMines** [comment]
As part of this, should investigate whether grid names for merged grids are "remembered".  Likely not, but you could conditionally check if the name should be updated from the script

**Comment by jgersti** [comment]
merging/unmerging (and falling apart from taking damage) creates new grids. And I believe the largest chunk "wins" (it sets the name on merge/keeps the name on unmerge).
