### ISSUE TITLE
[Feature Request] Rotor (and Piston) support to remove limits

### ISSUE THREAD

**Issue by MerlinofMines** [MerlinofMines/EasyCommands#260]
**Is your feature request related to a problem? Please describe.**
Currently there isn't a clear way to remove the upper/lower limits on Rotors, Hinges and Pistons.  It'd be nicer if we could disable

**Describe the solution you'd like**
Something like:

`turn off "My Rotor" upper limit` should do fine.

**Additional context**
Probably just need to add a ReturnTyped handler on the existing limit property handler, and look for boolean = false to indicate to remove the limit.

**Comment by CorwinMacGregor** [comment]
it was either Malware or Digi that pointed out the code in the vanilla stuff concerning this:  if either of the rotor's limit values are set to more than plus-or-minus 2pi radians, that limit is treated as "Unlimited", and internally set to MIN_ or MAX_FLOAT.  thus, setting the limit to ±361 is sufficient.  would be nice to have "unlimited" as a keyword, though, for setting rotor limit angles
