### ISSUE TITLE
[Feature Request] Reopen issue #260 in light of recent comment

### ISSUE THREAD

**Issue by CorwinMacGregor** [MerlinofMines/EasyCommands#268]
Comment in closed issue #260 implies more natural support of setting rotor limits to "unlimited" by parsing argument to setting a rotor's limit properties to a string of "unlimited" as a value less than -2π (-360°) or greater than +2π (360°).

I would imagine that internally, a typecheck on the argument to setting a rotor's upper or lower limit could be typechecked, and if the result does not translate to a number, check if the translation is to a string of value "unlimited".  if so, then
  if target property is lower limit, set property to equivalent of -361°
  if target property is upper limit, set property to equivalent of 361°

**Comment by CorwinMacGregor** [comment]
https://discord.com/channels/125011928711036928/216219467959500800/1123573804321472552

**Comment by MerlinofMines** [comment]
I implemented support for this in merge request #261.  It uses a boolean rather than "unlimited".  Check out the related tests to see examples, and the docs were also updated.  Marking as closed.
